/* eslint-disable no-template-curly-in-string */
/* Generated by .claude/scripts/gen-fidelity-lists.cjs from the t13-daily-work-order-report NeoLoad tree — do not hand-edit.
   Regenerate after re-recording. Tier-2 (UI chrome) requests fired behind -e FIDELITY.
   The ${...} tokens are correlation placeholders substituted at fire time. */
import { ChromeRequest } from '../../utils/exports/types.exp.ts';

export const dailyWorkOrderReportChrome: { [step: string]: ChromeRequest[][] } = {};
