/* Generated by .claude/scripts/gen-fidelity-lists.cjs from the t19-opportunity-conversion-report NeoLoad tree — do not hand-edit.
   Regenerate after re-recording. Tier-2 (UI chrome) requests fired behind -e FIDELITY.
   The ${...} tokens are correlation placeholders substituted at fire time. */
import { ChromeRequest } from '../../utils/exports/types.exp.ts';

export const opportunityConversionReportChrome: { [step: string]: ChromeRequest[][] } = {};
