/* Generated by .claude/scripts/gen-pool.cjs from the NeoLoad P_Binary pool
   (@p_@binary.xml (inline Base64 <values>), column values, 2 rows) — do not hand-edit.
   Regenerate when the NeoLoad data file changes. */

export const binaryValues: string[] = ['True', 'False'];
