/* Generated by .claude/scripts/gen-pool.cjs from the NeoLoad P_CrystalReport_Scope pool
   (@p_@crystal@report_@scope.xml (inline Base64 <values>), column Value, 2 rows) — do not hand-edit.
   Regenerate when the NeoLoad data file changes. */

export const crystalReportScopes: string[] = ['X', 'I'];
