/* Generated by .claude/scripts/gen-pool.cjs from the NeoLoad P_26_3_DailyFunction_Payload pool
   (variables/version_26_3/P_26_3_DailyFunction_Payload.txt, columns EventStartStatus, EventEndStatus, UserID, 2 rows) — do not hand-edit.
   Regenerate when the NeoLoad data file changes. */

export const dailyFunctionPayloads = [
  { EventStartStatus: '0A', EventEndStatus: 'ZQ', UserID: 'LANDONV' },
  { EventStartStatus: '09', EventEndStatus: 'UN', UserID: 'RYANC' },
];
