/* Generated by .claude/scripts/gen-pool.cjs from the NeoLoad P_26_3_DataScript_VoucherProcessing pool
   (variables/version_26_3/P_26_3_DataScript_VoucherProcessing.txt, column supplierName, 4 rows) — do not hand-edit.
   Regenerate when the NeoLoad data file changes. */

export const dataScriptVoucherProcessing: string[] = ['Blighten Supplies', 'Deltavalve Canada', 'PT_1_Supplier', 'PT_2_Supplier'];
