/* Generated by .claude/scripts/gen-pool.cjs from the NeoLoad P_DetailGeneralLedgerFormat pool
   (@p_@detail@general@ledger@format.xml (inline Base64 <values>), column reportFormat, 3 rows) — do not hand-edit.
   Regenerate when the NeoLoad data file changes. */

export const detailGeneralLedgerFormats: string[] = ['A', 'E', 'F'];
