/* Generated by .claude/scripts/gen-pool.cjs from the NeoLoad P_26_3_Payment_Payload pool
   (variables/version_26_3/P_26_3_Payment_Payload.txt, columns UserID, Account, Payseq, CC, 21 rows) — do not hand-edit.
   Regenerate when the NeoLoad data file changes. */

export const paymentPayloads = [
  { UserID: 'VIMALR', Account: '00147711', Payseq: '802', CC: 'XXXXXXXXX' },
  { UserID: 'VIMALR', Account: '00150963', Payseq: '640', CC: 'XXXXXXXXX' },
  { UserID: 'VIMALR', Account: '905', Payseq: '1', CC: '41XXXXXXXXXX1111' },
  { UserID: 'VIMALR', Account: '00160202', Payseq: '7', CC: 'XXXXXXXXX' },
  { UserID: 'VIMALR', Account: '00160202', Payseq: '6', CC: 'XXXXXXXXX' },
  { UserID: 'VIMALR', Account: '00160202', Payseq: '3', CC: 'XXXXXXXXX' },
  { UserID: 'VIMALR', Account: '00045244', Payseq: '40', CC: '41XXXXXXXXXX1111' },
  { UserID: 'VIMALR', Account: '00049741', Payseq: '24', CC: '41XXXXXXXXXX1111' },
  { UserID: 'VIMALR', Account: '00065517', Payseq: '71', CC: '40XXXXXXXXXX8873' },
  { UserID: 'VIMALR', Account: '00054279', Payseq: '58', CC: '42XXXXXXX2222' },
  { UserID: 'VIMALR', Account: '00065517', Payseq: '25', CC: '42XXXXXXX2222' },
  { UserID: 'VIMALR', Account: '00065517', Payseq: '21', CC: '42XXXXXXX2222' },
  { UserID: 'USIADMIN', Account: '00042261', Payseq: '1335', CC: '41XXXXXXXXXX1111' },
  { UserID: 'RYANC', Account: '00147134', Payseq: '413', CC: '41XXXXXXXXXX1111' },
  { UserID: 'ROHITL', Account: '00150664', Payseq: '4', CC: 'XXXXXXXXX' },
  { UserID: 'MICHAEL', Account: '00132720', Payseq: '409', CC: '1111' },
  { UserID: 'MARYNAM', Account: '00147134', Payseq: '405', CC: '41XXXXXXXXXX1111' },
  { UserID: 'LANDONV', Account: '00045244', Payseq: '51', CC: '41XXXXXXXXXX1111' },
  { UserID: 'JOEK', Account: '00046106', Payseq: '12', CC: 'XXXXXXXXX' },
  { UserID: 'BETHC', Account: '00147135', Payseq: '246', CC: '41XXXXXXXXXX1111' },
  { UserID: 'ABBIEK', Account: '00147134', Payseq: '413', CC: '41XXXXXXXXXX1111' },
];
