/* Generated by .claude/scripts/gen-pool.cjs from the NeoLoad P_SearchRandomEvent pool
   (@p_@search@random@event.xml (inline Base64 <values>), column keyword, 25 rows) — do not hand-edit.
   Regenerate when the NeoLoad data file changes. */

export const eventSearchKeywords: string[] = [
  'performance',
  'venue',
  'event',
  'sport',
  'concert',
  'hall',
  'function',
  'center',
  'party',
  'wedding',
  'conference',
  'seminar',
  'class',
  'lunch',
  'dinner',
  'football',
  'soccer',
  'basketball',
  'booking',
  'contract',
  'exhibition',
  'dates',
  'show',
  'club',
  'demo',
];
