# Pipeline to generate the "Momentus k6 Performance Tests" artifact when a PR is created targeting the main branch.
# Pipeline also re-runs whenever new commits are pushed to the existing PR.

trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  site: 'AT'
  releaseVersion: '26_2'

jobs:
  - job: Build
    timeoutInMinutes: 5
    steps:
      - template: ../templates/build-steps.yml
