# Pipeline to generate the "Momentus k6 Performance Tests" artifact and run SonarQube analysis when code is merged into main.
# Pipeline does not trigger on PRs — use k6-tests-ci-dev.yml for PR validation.

trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  site: 'AT'
  releaseVersion: '26_2'

jobs:
  - job: Build
    timeoutInMinutes: 10
    steps:
      - checkout: self
        fetchDepth: 0
        displayName: 'Full Git checkout for SonarQube blame analysis'

      - task: SonarQubePrepare@8
        displayName: 'Prepare SonarQube Analysis Configuration'
        enabled: true
        continueOnError: true
        inputs:
          SonarQube: 'SonarQube Community'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'performance-k6'
          cliProjectName: 'performance-k6'
          cliSources: '.'

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Removes sonar.branch.name from scanner params as SonarQube Community edition does not support branch analysis.

            $sonarParams = $env:SONARQUBE_SCANNER_PARAMS | ConvertFrom-Json
            $sonarParams.PSObject.Properties.Remove('sonar.branch.name')
            $params = $sonarParams | ConvertTo-Json -Compress
            Write-Host "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$params"

      - template: ../templates/build-steps.yml

      - task: SonarQubeAnalyze@8
        displayName: 'Run Code Analysis'
        enabled: true
        continueOnError: true
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'

      - task: SonarQubePublish@8
        displayName: 'Publish Quality Gate Result'
        enabled: true
        continueOnError: true
        inputs:
          pollingTimeoutSec: '300'
