// Generate a source/data/pools/<name>.data.ts module from a NeoLoad data pool — the write half of the
// pool port, so pool values are extracted mechanically instead of transcribed from the head of a file
// (the same "generate, don't transcribe" rule gen-payload-builder.cjs applies to captured bodies).
//
// Usage:
//   node .claude/scripts/gen-pool.cjs <path in the NeoLoad project> <P_VarName> <column> <outFile> [flags]
//   node .claude/scripts/gen-pool.cjs ../performance P_26_2_CopyEvents eventName source/data/pools/copy-events.data.ts
//
//   <column>    one column name/index → string[];  a comma-separated list → array of row objects
//   --export N  export name (default: camelCase of the output basename)
//   --unique    drop duplicate rows (default keeps every row, as NeoLoad cycles them)
//
// Run `node .claude/scripts/neoload-vars.cjs "<VU tree>"` first — it prints the ready-to-run command
// for every pool a VU references. Deterministic; the only writer is the output file.

const fs = require('fs');
const path = require('path');
const { findProjectRoot, loadDefs, resolveDef, poolValues } = require('./neoload-vars.cjs');

const argv = process.argv.slice(2);
const flag = (name) => {
  const i = argv.indexOf(name);
  if (i < 0) return null;
  const v = argv[i + 1];
  argv.splice(i, 2);
  return v;
};
const bool = (name) => {
  const i = argv.indexOf(name);
  if (i < 0) return false;
  argv.splice(i, 1);
  return true;
};

const exportOverride = flag('--export');
const unique = bool('--unique');
const [target, varName, columnArg, outFile] = argv;

if (!target || !varName || !columnArg || !outFile) {
  console.error(
    'usage: node .claude/scripts/gen-pool.cjs <path in NeoLoad project> <P_VarName> <column[,column…]> <outFile> [--export N] [--unique]',
  );
  process.exit(1);
}

const root = findProjectRoot(target);
if (!root) {
  console.error(`no NeoLoad project root (a dir containing team/variables) at or above: ${target}`);
  process.exit(1);
}
const def = loadDefs(root).get(varName);
if (!def) {
  console.error(`no definition for ${varName} in ${path.join(root, 'team', 'variables')}`);
  process.exit(1);
}
const resolved = resolveDef(def, root);
if (resolved.kind !== 'pool') {
  console.error(
    `${varName} is a ${resolved.kind} (${resolved.tag}), not a data pool — it belongs in source/config/ or is regenerated per iteration`,
  );
  process.exit(1);
}
if (resolved.error) {
  console.error(`cannot resolve ${varName}: ${resolved.error}`);
  process.exit(1);
}
if (resolved.warning) console.error(`WARNING: ${resolved.warning}`);

const columns = columnArg
  .split(',')
  .map((c) => c.trim())
  .filter(Boolean);
const camel = (s) =>
  s
    .replace(/\.data\.ts$/, '')
    .split(/[-_.\s]+/)
    .filter(Boolean)
    .map((w, i) => (i === 0 ? w[0].toLowerCase() + w.slice(1) : w[0].toUpperCase() + w.slice(1)))
    .join('');
const exportName = exportOverride || camel(path.basename(outFile));

// Single-quoted where prettier would prefer it, double-quoted when the value carries an apostrophe.
const lit = (s) => {
  const json = JSON.stringify(s);
  if (s.includes("'") && !s.includes('"')) return json;
  return `'${json.slice(1, -1).replace(/\\"/g, '"').replace(/'/g, "\\'")}'`;
};

const header = (detail) =>
  `/* Generated by .claude/scripts/gen-pool.cjs from the NeoLoad ${varName} pool\n   (${resolved.source}, ${detail}) — do not hand-edit.\n   Regenerate when the NeoLoad data file changes. */`;

let body;
let count;
if (columns.length === 1) {
  let values = poolValues(resolved, columns[0]);
  if (unique) values = [...new Set(values)];
  count = values.length;
  body = `${header(`column ${columns[0]}, ${count} rows`)}\n\nexport const ${exportName}: string[] = [\n${values.map((v) => `  ${lit(v)},`).join('\n')}\n];\n`;
} else {
  const perColumn = columns.map((c) => poolValues(resolved, c));
  const len = Math.min(...perColumn.map((v) => v.length));
  let rows = Array.from({ length: len }, (_, i) => columns.map((c, k) => [c, perColumn[k][i]]));
  if (unique) {
    const seen = new Set();
    rows = rows.filter((r) => {
      const key = JSON.stringify(r);
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  }
  count = rows.length;
  const entries = rows.map((r) => `  { ${r.map(([c, v]) => `${c}: ${lit(v)}`).join(', ')} },`).join('\n');
  body = `${header(`columns ${columns.join(', ')}, ${count} rows`)}\n\nexport const ${exportName} = [\n${entries}\n];\n`;
}

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, body);
console.log(`wrote ${outFile}`);
console.log(`  export ${exportName}  ${count} rows  from ${varName}.${columns.join('+')}  (${resolved.source})`);
