/* eslint-disable no-template-curly-in-string */
/* Generated by scripts/gen-fidelity-lists.js from the copy-service-orders NeoLoad tree — do not hand-edit.
   Regenerate after re-recording. Transport (non-api/non-static) requests fired behind -e FIDELITY.
   The ${...} tokens are correlation placeholders substituted at fire time. */
import { ChromeRequest } from '../../utils/exports/types.exp.ts';

export const copyServiceOrdersTransport: { [step: string]: ChromeRequest[] } = {
  '01': [
    {
      method: 'GET',
      path: '/Content/css/backOffice?v=${C_backOffice_version}&v=${C_USI_Version}&v=${C_USI_Version}',
    },
    {
      method: 'GET',
      path: '/Content/css/splash_bundle?v=&v=${C_USI_Version}&v=${C_USI_Version}',
    },
    {
      method: 'GET',
      path: '/Content/css?v=${C_css_version}',
    },
    {
      method: 'GET',
      path: '/scripts/modernizr?v=${C_modernizr_version}',
    },
    {
      method: 'GET',
      path: '/scripts/wijmo/controls/cultures/english?v=${C_english_version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}&v=${C_USI_Version}',
    },
  ],
  '02': [
    {
      method: 'GET',
      path: '/fonts/usifont-messageIcons.ttf?v=3.2.1',
    },
    {
      method: 'POST',
      path: '/app85.cshtml?OrgCode=10&ApplicationDisplay=1&SingleSignOnToken=${C_TokenID}&VisualEffects=0&SignInTimings=',
    },
    {
      method: 'GET',
      path: '/signalr/start?transport=webSockets&clientProtocol=2.1&connectionToken=${C_ConnectionToken}&connectionData=[{&quot;name&quot;:&quot;globalnavnotificationhub&quot;}]&_=${P_EpochTimestamp}',
    },
  ],
  '08': [
    {
      method: 'POST',
      path: '/app85.cshtml?Logout=Y&ClientAppCategory=10',
    },
  ],
};
