/* Generated by .claude/scripts/gen-fidelity-lists.cjs from the badge-report NeoLoad tree — do not hand-edit.
   Regenerate after re-recording. Transport (non-api/non-static) requests fired behind -e FIDELITY.
   The ${...} tokens are correlation placeholders substituted at fire time. */
import { ChromeRequest } from '../../utils/exports/types.exp.ts';

export const badgeReportTransport: { [step: string]: ChromeRequest[][] } = {};
