/* Generated by scripts/gen-fidelity-lists.js — tier-3 static content fired behind -e FIDELITY=full. */
import { StaticRequest } from '../../utils/exports/types.exp.ts';

export const bookEventStatic: { [step: string]: StaticRequest[] } = {
  '11': [
    {
      path: '/app/enterprise-dist/components/floating/popover/popover.component.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu.component.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu-option.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu-option-label.html',
    },
  ],
  '01': [
    {
      path: '/Scripts/aurelia/resources/elements/draggable/draggable.html',
    },
    {
      path: '/Scripts/aurelia/resources/index.js',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/Popover--ProgressIndicator/ProgressIndicator.html',
    },
    {
      path: '/app/enterprise-dist/views/signIn.html',
    },
    {
      path: '/app/node_components/localforage/dist/localforage.min.js',
    },
    {
      path: '/content/images/favicon.ico',
    },
    {
      path: '/scripts/jsonh.js',
    },
    {
      path: '/app/node_components/lodash/lodash.min.js',
    },
    {
      path: '/app/enterprise-dist/public/SPA/controls/syncfusion-rte.js',
    },
  ],
  '02': [
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Button/button.css',
    },
    {
      path: '/app/enterprise-dist/components/accordion/accordion.component.html',
    },
    {
      path: '/app/enterprise-dist/components/overlay/overlay.component.html',
    },
    {
      path: '/app/enterprise-dist/components/toast/toast.component.html',
    },
    {
      path: '/app/enterprise-dist/components/toast/toast.component.js',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/ButtonContentTemplate/ButtonContentTemplate.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/ButtonGadget/ButtonGadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/Gadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/TextGadget/TextGadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/MenuButton/MenuButton.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/leftGlobalMobileNav/leftGlobalMobileNav.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/leftGlobalNav/leftGlobalNav.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/siteHeader/siteHeader.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/home/home.html',
    },
    {
      path: '/app/enterprise-dist/pages/home-page/home-page.html',
    },
    {
      path: '/app/enterprise-dist/views/shell.html',
    },
    {
      path: '/app/enterprise-dist/components/accordion/accordion.interfaces.js',
    },
  ],
  '03': [
    {
      path: '/app/enterprise-dist/components/window-message/window-message.component.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/bookingCalendar/bookingCalendar.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/bookingCalendar/pendingGrid/bookingsGrid.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/bookingCalendar/ribbon/calendarRibbon.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/bookingCalendar/ribbon/controls/button.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/bookingCalendar/ribbon/controls/comboBox.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/bookingCalendar/ribbon/controls/datePicker.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/bookingCalendar/ribbon/controls/switch.html',
    },
    {
      path: '/app/enterprise-dist/pages/list-page/list-page.html',
    },
    {
      path: '/app/enterprise-dist/viewmodels/genericList.js',
    },
    {
      path: '/app/enterprise-dist/views/pageFooter.html',
    },
  ],
  '04': [
    {
      path: '/app/enterprise-dist/framework/common.blocks/CalendarPicker/CalendarHeader/CalendarHeader.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/CalendarPicker/CalendarPicker.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/CalendarPicker/Day/Day.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/CalendarPicker/Day/Day.js',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/CalendarPicker/Decade/Decade.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/CalendarPicker/Month/Month.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/CalendarPicker/Year/Year.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.ComboBox/Dropdown/Dropdown.css',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.DatePicker/PopupPicker/PopupPicker.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/PopoverHost/PopoverHost.html',
    },
  ],
  '06': [
    {
      path: '/app/enterprise-dist/components/drawer/drawer.component.html',
    },
    {
      path: '/app/enterprise-dist/controls00/layoutControls/editLayoutContainer/editLayoutContainer.html',
    },
    {
      path: '/app/enterprise-dist/controls00/layoutControls/sectionContainer/sectionContainer.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/Tabs/tabs.html',
    },
    {
      path: '/app/enterprise-dist/views/USISectionMenu.html',
    },
    {
      path: '/app/enterprise-dist/views/genericDetail.html',
    },
    {
      path: '/app/enterprise-dist/views/genericPageFooter.html',
    },
    {
      path: '/app/enterprise-dist/views/genericPageNav.html',
    },
    {
      path: '/app/enterprise-dist/views/genericPageNavToolbar.html',
    },
    {
      path: '/app/enterprise-dist/views/genericPageSearch.html',
    },
    {
      path: '/app/enterprise-dist/views/genericSearch.html',
    },
  ],
  '08': [
    {
      path: '/app/enterprise-dist/components/floating/peek/peek.component.html',
    },
    {
      path: '/app/enterprise-dist/components/floating/popover/popover.component.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu.component.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu-container.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu-option.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu-option-label.html',
    },
    {
      path: '/app/enterprise-dist/components/modal/modal.component.html',
    },
    {
      path: '/app/enterprise-dist/framework/Common.Blocks/ButtonContentTemplate/ButtonContentTemplate.html',
    },
    {
      path: '/app/enterprise-dist/framework/Common.Blocks/MenuButton/MenuButton.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/genericMultipleDetail/genericMultipleDetail.html',
    },
    {
      path: '/app/enterprise-dist/views/genericList.html',
    },
  ],
};
