/* Generated by scripts/gen-fidelity-lists.js — tier-3 static content fired behind -e FIDELITY=full. */
import { StaticRequest } from '../../utils/exports/types.exp.ts';

export const roomDiagramUploadStatic: { [step: string]: StaticRequest[] } = {
  '01': [
    {
      path: '/Scripts/aurelia/resources/elements/draggable/draggable.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/Popover--ProgressIndicator/ProgressIndicator.html',
    },
    {
      path: '/app/enterprise-dist/views/signIn.html',
    },
    {
      path: '/content/images/favicon.ico',
    },
    {
      path: '/content/images/splashscreen/momentus-logo-mark-reverse-rgb.svg',
    },
  ],
  '02': [
    {
      path: '/app/enterprise-dist/components/accordion/accordion.component.html',
    },
    {
      path: '/app/enterprise-dist/components/floating/tooltip/tooltip.component.html',
    },
    {
      path: '/app/enterprise-dist/components/overlay/overlay.component.html',
    },
    {
      path: '/app/enterprise-dist/components/toast/toast.component.html',
    },
    {
      path: '/app/enterprise-dist/components/toast/toast.component.js',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/ButtonContentTemplate/ButtonContentTemplate.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/ButtonGadget/ButtonGadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/Gadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/KPIGaugeGadget/KPIGaugeGadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/PivotGadget/PivotGadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/TextGadget/TextGadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.Gadget/ViewGadget/ViewGadget.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.KPIGauge/KPIGauge.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/MenuButton/MenuButton.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/USIDataGridMenu/USIDataGridMenu.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/leftGlobalMobileNav/leftGlobalMobileNav.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/leftGlobalNav/leftGlobalNav.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/siteHeader/siteHeader.html',
    },
    {
      path: '/app/enterprise-dist/framework/windows/home/home.html',
    },
    {
      path: '/app/enterprise-dist/pages/home-page/home-page.html',
    },
    {
      path: '/app/enterprise-dist/views/shell.html',
    },
    {
      path: '/app/enterprise-dist/util00/OfficeApps.js',
    },
  ],
  '03': [
    {
      path: '/app/enterprise-dist/components/window-message/window-message.component.html',
    },
    {
      path: '/app/enterprise-dist/controls00/layoutControls/sectionContainer/sectionContainer.html',
    },
    {
      path: '/app/enterprise-dist/framework/common.blocks/FlexLayout.HyperLink/HyperLink.html',
    },
    {
      path: '/app/enterprise-dist/pages/list-page/list-page.html',
    },
    {
      path: '/app/enterprise-dist/views/genericList.html',
    },
    {
      path: '/app/enterprise-dist/views/genericPageNavToolbar.html',
    },
    {
      path: '/app/enterprise-dist/views/genericPageSearch.html',
    },
  ],
  '04': [
    {
      path: '/app/enterprise-dist/components/modal/modal.component.html',
    },
    {
      path: '/app/enterprise-dist/framework/Common.Blocks/ButtonContentTemplate/ButtonContentTemplate.html',
    },
    {
      path: '/app/enterprise-dist/framework/Common.Blocks/MenuButton/MenuButton.html',
    },
    {
      path: '/app/enterprise-dist/views/genericPageFooter.html',
    },
    {
      path: '/app/enterprise-dist/views/genericPageNav.html',
    },
    {
      path: '/app/enterprise-dist/views/genericSearch.html',
    },
    {
      path: '/app/enterprise-dist/views/pageFooter.html',
    },
  ],
  '05': [
    {
      path: '/app/enterprise-dist/framework/common.blocks/Tabs/tabs.html',
    },
    {
      path: '/app/enterprise-dist/views/USISectionMenu.html',
    },
    {
      path: '/app/enterprise-dist/views/genericDetail.html',
    },
  ],
  '06': [
    {
      path: '/app/enterprise-dist/components/floating/popover/popover.component.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu.component.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu-option.html',
    },
    {
      path: '/app/enterprise-dist/components/menu/menu-option-label.html',
    },
  ],
  '07': [
    {
      path: '/app/enterprise-dist/framework/windows/USIUploader/USIUploader.html',
    },
  ],
};
