/* Generated by .claude/scripts/gen-fidelity-lists.cjs — tier-3 static content fired behind -e FIDELITY=full. */
import { StaticRequest } from '../../utils/exports/types.exp.ts';

export const badgeReportStatic: { [step: string]: StaticRequest[][] } = {};
